FROM ubuntu:focal
COPY Dockerfile.minios-live.focal@install.sh /opt/install.sh
RUN chmod +x /opt/install.sh && /opt/install.sh && rm /opt/install.sh
VOLUME /build
WORKDIR /build/minios-live
CMD ["/build/minios-live/autoinstall", "-"]
