FROM ubuntu:bionic
COPY Dockerfile.minios-live.0@install.sh /opt/install.sh
RUN chmod +x /opt/install.sh
RUN /opt/install.sh
RUN rm /opt/install.sh
VOLUME /build
WORKDIR /build
CMD ["/build/minios-live/autoinstall", "-"]
